### ISSUE TITLE
How to use the package?

### ISSUE THREAD

**Issue by cgueret** [vdorie/npci#2]
Could you please clarify how to use the package? I would like to generate 1k files similar to those found in https://github.com/claudiashi57/dragonnet/tree/master/dat/ihdp/csv in order to compare my approach to Dragonnet.

**Comment by vdorie** [comment]
Dragonnet should supply this information, as that was not the intended use of this repository and it contains only experimental and abandoned code that was never used in any publication. I have no idea what transformations they did to the data, or under what conditions they generated their samples. Briefly:

1. Install the package.
2. Modify [runLocally.R](../blob/master/examples/ihdp_sim/runLocally.R) to specify the desired simulation settings and set the `methods` to something new, like `"generate_csvs"`
3. Modify the method `if`/`else` chain in [runJob.R](../blob/master/examples/ihdp_sim/runJob.R) to handle the new method,`"generate_csvs"`, and have it write out the csv files somewhere
4. Execute `runLocally.R`

**Comment by cgueret** [comment]
Okay, thanks!
